#!/bin/bash
# This script is for kernel upgrade of RHEL 8 prepared by kenechukwu
sleep 5
echo
uname -sr >> ~/kernelversion
echo
sleep 5
echo
echo " ***** Enabling EPEL Repository ***** "
echo
sleep 5
echo
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
echo
sleep 5
echo
#rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
rpm -Uvh https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
echo
sleep 5
echo
echo " ***** Listing available packages ***** "
echo
sleep 5
yum --disablerepo="*" --enablerepo="elrepo-kernel" list available
echo
sleep 5
echo
echo " ***** Installing the Latest Kernel ***** "
echo
sleep 5
echo
yum -y --enablerepo=elrepo-kernel install kernel-ml
echo
sleep 5
echo
echo "*** New Kernel successfully installed ***"
echo
sleep 5

echo " ***** Next Set the default grub ***** "
echo " *****Open and edit the file /etc/default/grub and set GRUB_DEFAULT=0. This means that the first kernel in the GRUB initial screen will be used as default.***** "
echo
sed -i 's/GRUB_DEFAULT=saved/GRUB_DEFAULT=0/g' /etc/default/grub
echo
sleep 5
echo
echo "***** Next, run the following command to recreate the kernel configuration. *****"
echo
sleep 5
echo
grub2-mkconfig -o /boot/grub2/grub.cfg
echo
sleep 5
echo
echo uname -sr >> ~/kernelversion
echo
sleep 5

echo " ***** Kernel Updrade Successful *****"
sleep 10
echo
reboot



